### ISSUE TITLE
Parse DNS Fields

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/endpoint-package#83]
Create a pipeline that adds the following fields:

![image](https://user-images.githubusercontent.com/56361221/93636309-b2ae6780-f9c1-11ea-957b-5930487cc563.png)

These fields are already populated by the elastic endgame endpoint.

Take a look at these docs for writing the ingest pipeline to do the parsing: https://www.elastic.co/guide/en/elasticsearch/reference/current/grok-processor.html

Related:
https://github.com/elastic/endpoint-dev/issues/7136

**Comment by james-elastic** [comment]
AC: A user will be able to see the three fields from the screenshot.

**Comment by jonathan-buttner** [comment]
PR is here: https://github.com/elastic/endpoint-package/pull/88

It populates `dns.question.type` and `dns.question.name`. I looked into populating `dns.question.registered_domain` but it'd be pretty complicated to get it right using painless scripting I think according to the ecs spec: https://github.com/elastic/ecs/blob/master/schemas/dns.yml#L102

Also `dns.question.name` doesn't full adhere to the ecs spec with regards to having non-printable characters: https://github.com/elastic/ecs/blob/master/schemas/dns.yml#L74

**Comment by jonathan-buttner** [comment]
Closing this ticket as the PR above was merged.
